import Head from 'next/head'
export default function Header(){
   return( <Head>
        <title>Saiyad Mahammadakil</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Fevicon.png" />
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css"></link>
      </Head>
      )
}