import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Saiyad Mahammadakil</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/fevicon.png" />
      </Head>

      <main className={styles.main}>
        Hello
      </main>

      <footer className={styles.footer}>
       Saiyad_akil
      </footer>
    </div>
  )
}
